### ISSUE TITLE
import processing needs to handle non-trivial cases

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#10]
The current implementation (in `Recording.do_import`) isn't sophisticated enough for anything but the most trivial cases. It's very easy to make it go into an infinite recursion. The simplest fix for that recursion is just checking `sys.modules` to see if the module is already loaded. This fails if the module got renamed when loaded (e.g. `import ... as ...`), so this probably isn't enough either.

**Comment by kgilpin** [comment]
Maybe you can identify modules by source location? This tends to be stable.

**Comment by apotterri** [comment]
That's a good idea. I'll see if I can take advantage of that.

**Comment by apotterri** [comment]
Looks like that's not going to fix the current approach. The problem is that our hook gets called before the python machinery has located the file that contains the module, so there's no way to know whether that matches a previous import.

I believe there's a different, only slightly more complicated, approach we can take that will let us hook into the machinery *after* the module has been loaded. I'll be investigating that next.
