### ISSUE TITLE
flask normalized_path_info is not formatted correctly

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#104]
It should match the example in the spec: https://github.com/applandinc/appmap#http-server-request-call-attributes .

**Comment by dividedmind** [comment]
I'm not sure I agree. I thought the spec purposely leaves the format undefined, so as to allow the implementations to use whatever's idiomatic for the platform.

**Comment by kgilpin** [comment]
What does it look like in flask now?

It would be nice if they were consistent across the languages.

We do need to be able to consistently transform them into Swagger format.

**Comment by dividedmind** [comment]
> What does it look like in flask now? It would be nice if they were consistent across the languages. We do need to be able to consistently transform them into Swagger format.

Flask and Django use a similar format, for example: `/user/<login:str>/posts/<postid:int>` (or something along those lines). I don't think it's a good idea to force Rails format universally. It can be confusing to users and lose information. If swagger needs specific format, then it should transform the appmap appropriately; in the language-specific clients is the wrong place for that unification IMO.

And if we do want it to be unified, then we need to document the expected format in the appmap spec.

**Comment by kgilpin** [comment]
We decided to use Swagger format universally.

**Comment by dividedmind** [comment]
> We decided to use Swagger format universally.

Ah, ok, I see it now :) Thanks!
