### ISSUE TITLE
Relax python version requirement to 3.5

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#40]
We'll greatly expand our reach if we can support older python versions. 3.4 seems like a good target.

This will also require removal of orjson, so closing #36, too.

**Comment by virajkanwade** [comment]
@apotterri
https://www.python.org/downloads/release/python-3410/
>>> Python 3.4 has reached end-of-life. Python 3.4.10 is the final release of 3.4.
>>> Python 3.4.10 was released on March 18th, 2019.
>>> Python 3.4.10 is the final release in the Python 3.4 series. As of this release, the 3.4 branch has been retired, no further changes to 3.4 will be accepted, and no new releases will be made. This is standard Python policy; Python releases get five years of support and are then retired.

https://www.python.org/downloads/release/python-3510/
>>> Python 3.5 has reached end-of-life. Python 3.5.10 is the final release of 3.5.
>>> Python 3.5.10 was released on September 5th, 2020.
>>> Python 3.5.10 is the final release in the Python 3.5 series. As of this release, the 3.5 branch has been retired, no further changes to 3.5 will be accepted, and no new releases will be made. This is standard Python policy; Python releases get five years of support and are then retired.

**Comment by virajkanwade** [comment]
@apotterri just in case https://realpython.com/intro-to-pyenv/ `Managing Multiple Python Versions With pyenv`

**Comment by apotterri** [comment]
Yeah, I know 3.5 has been EOLed. (Supporting 3.4 would require too many changes, so it's no longer under consideration.)

We want to be able to map as many projects as possible, and some subset of them still use 3.5. I expect we'll be able to drop support for it at some point.

**Comment by apotterri** [comment]
Yes, I'm using `pyenv` to manage my python environments.
