### ISSUE TITLE
appmap package is classified in the pypi.org repository

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-python#62]
Development Status :: 4 - Beta
Framework :: Django
Framework :: Pytest
License :: OSI Approved :: MIT License
Programming Language :: Python
Programming Language :: Python :: 3
Topic :: Software Development
Topic :: Software Development :: Debuggers
Topic :: Software Development :: Documentation

**Comment by apotterri** [comment]
@ptrdvrk Please take a a look at https://pypi.org/project/appmap/0.5.0/ for the current classifiers.
