### ISSUE TITLE
SQLAlchemy integration captures sql_query events

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#64]

**Comment by virajkanwade** [comment]
Unlike Django (https://github.com/applandinc/appmap-python/commit/c458dcbfdca1bb856f12364124278080fc854c54) flask does not have inbuilt orm or db signals.

Sqlalchemy is commonly used (though some choose direct db libs like psycopg2 or pymysql) in conjunction with flask.

sqlalchemy events could be used https://docs.sqlalchemy.org/en/14/core/event.html

**Comment by apotterri** [comment]
Hooking sqlalchemy events seems like a good place to start. Thanks for this.

**Comment by virajkanwade** [comment]
#75 sample code

**Comment by dividedmind** [comment]
Thanks @virajkanwade for the sketch, this has now been implemented.
