### ISSUE TITLE
Misago failing tests

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-python#79]
Misago tests are failing with the `free-functions_20210310` branch client.

Failing tests:
- misago/users/tests/test_twitter_profilefield.py
- misago/users/tests/test_user_editdetails_api.py
- misago/core/tests/test_chunk_queryset.py
- misago/themes/admin/tests/test_creating_and_editing_themes.py
- misago/users/tests/test_bio_profilefield.py
- misago/users/tests/test_gender_profilefield.py

appmap.yml:
```yaml
name: misage
packages:
  - path: misago
```

[misago_test_errors.log](https://github.com/applandinc/appmap-python/files/6313505/misago_test_errors.log)

**Comment by dividedmind** [comment]
I'm not getting any failures anymore with #86 and #87.

**Comment by dividedmind** [comment]
Fixed by #86 and #87.
