### ISSUE TITLE
ValueError: no signature found for builtin <functools._lru_cache_wrapper object at 0x7fffe7751768>

### ISSUE THREAD

**Issue by lovetoburnswhen** [applandinc/appmap-python#80]
Getting this with Python 3.7. Likely related to https://bugs.python.org/issue1748064 ?

Edit: Onlyl seems to work when I use more restrictive paths in appmap.yml

**Comment by apotterri** [comment]
@Frank5000 thanks very much for reporting this. We'll need to update `appmap-python` so it expects missing signatures for built-in functions.

Can you share what project you're trying to map, and what your appmap.yml looks like?

**Comment by dividedmind** [comment]
With 087e57c55418ecf961f38faaf7f6e7cd0ab93bbe lru_cache no longer raises an error. 

(Note arguments still aren't captured; with missing signature `parameters` ends up as `[]`. I've opened #124 to track this.)
