### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by dividedmind** [applandinc/appmap-python#94]
It's over five years old and seven months after its end of life: https://endoflife.date/python

It breaks builds often and requires frequent special cases and special fixes.

**Comment by kgilpin** [comment]
We should drop it if it's EOL. That is what we've done with Ruby.

In the future if we have more resources we can consider re-adding support.
But for now, we should not bother with EOL releases, it's too much work for
us right now.

**Comment by dividedmind** [comment]
> We should drop it if it's EOL. That is what we've done with Ruby. In the future if we have more resources we can consider re-adding support. But for now, we should not bother with EOL releases, it's too much work for us right now.

That's what I've been saying before, I don't remember what the argument to keep it was. @apotterri or @ptrdvrk, do you remember?

**Comment by apotterri** [comment]
Yes. @ptrdvrk asked for it, in the interest of being able to map more projects.

@ptrdvrk is it ok to drop support for it?

**Comment by ptrdvrk** [comment]
OK, let's drop 3.5.
